log_period_start:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    date:
      selector:
        date:

log_period_end:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    date:
      selector:
        date:

add_period:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    start:
      required: true
      selector:
        date:
    end:
      selector:
        date:

log_ovulation:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    date:
      selector:
        date:
    method:
      default: other
      selector:
        select:
          translation_key: ovulation_method
          options:
            - lh_test
            - temperature
            - ultrasound
            - symptoms
            - other

delete_ovulation:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    date:
      required: true
      selector:
        date:

delete_period:
  fields:
    config_entry:
      selector:
        config_entry:
          integration: menstrual_cycle
    date:
      required: true
      selector:
        date:
